// Curated icon names for worldbuilding concepts, shown in the picker's
// "Suggested" section. Names are validated against ICON_MAP at render time,
// so a name missing from the installed Phosphor version is silently skipped.

export const SUGGESTED_ICONS: string[] = [
  // people & society
  'User',
  'Users',
  'UsersThree',
  'Crown',
  'Handshake',
  'GraduationCap',
  'Scales',
  'Ghost',
  'Skull',
  // places
  'CastleTurret',
  'MapPin',
  'Mountains',
  'Tree',
  'Bank',
  'Church',
  'Door',
  'Tent',
  'Wall',
  'Globe',
  'Planet',
  // conflict & objects
  'Sword',
  'Shield',
  'Key',
  'Coin',
  'Coins',
  'Diamond',
  'Flask',
  'Scroll',
  'Book',
  'BookOpen',
  'Feather',
  // creatures
  'PawPrint',
  'Bird',
  'Fish',
  'Horse',
  'Butterfly',
  'Bug',
  // events & forces
  'Flag',
  'Lightning',
  'Fire',
  'Snowflake',
  'Moon',
  'Sun',
  'Star',
  'Sparkle',
  'MagicWand',
  'Hourglass',
  'Compass',
  'Anchor',
  'Sailboat',
];
